IV=65534:REM INTERRUPT VECTOR
SC=65375:REM SCREEN/SWAPPER
REM SET 40 COL FOR CX16 AND C128
IF PEEK(IV)=139 THEN POKE 780,3:SYS SC
IF PEEK(IV)=23 AND PEEK(215)=128 THEN SYS SC
REM MENU
QU$ = CHR$(34)
PRINT CHR$(147);CHR$(155);"FROM THE BOOK ";QU$;"COMMODORE 64 & 128"
PRINT "PROGRAMS FOR AMATEUR RADIO &ELECTRONICS";QU$;
PRINT " BY JOSEPH J. CARR"
PRINT CHR$(5)
PRINT "LOAD";QU$;"COIL-LOADED-SHOR";QU$;",8"
PRINT "LOAD";QU$;"VSWR-CALIBRATION";QU$;",8"
PRINT "LOAD";QU$;"SATELLITE-DISH-A";QU$;",8"
PRINT "LOAD";QU$;"RESISTORS-IN-SER";QU$;",8"
PRINT "LOAD";QU$;"CAPACITORS-IN-SE";QU$;",8"
PRINT "LOAD";QU$;"INDUCTORS-IN-SER";QU$;",8"
PRINT "LOAD";QU$;"ZENER-DIODE-VOLT";QU$;",8"
PRINT "LOAD";QU$;"RLC-NETWORKS";QU$;",8"
PRINT "LOAD";QU$;"DECIBEL-CALC";QU$;",8"
PRINT
PRINT
PRINT
PRINT
PRINT "RUN"
